# Generated by Django 2.2 on 2019-05-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preceptor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='preceptor',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='principal',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='Jane', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(default='Doe', max_length=50),
        ),
    ]
