# Generated by Django 2.2 on 2019-05-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegeApp', '0004_auto_20190528_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='division',
            field=models.CharField(choices=[('A', 'Division A'), ('B', 'Division B'), ('C', 'Division C'), ('D', 'Division D'), ('E', 'Division E')], default='A', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='shift',
            field=models.CharField(choices=[('turno mañana', 'Turno mañana'), ('turno tarde', 'Turno tarde'), ('turno noche', 'Turno noche')], default='turno mañana', max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(choices=[('Primer Año', 'Primer Año'), ('Segundo Año', 'Segundo Año'), ('Tercer Año', 'Tercer Año'), ('Cuarto Año', 'Cuarto Año'), ('Quinto Año', 'Quinto Año'), ('Sexto Año', 'Sexto Año'), ('Septimo Año', 'Septimo Año')], default='Primer Año', max_length=50),
        ),
    ]
